# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
#
options:
  debug:
    default: False
    description: Enable debug logging.
    type: boolean
  log-level:
    default: WARNING
    type: string
    description: Log level (WARNING, INFO, DEBUG, ERROR)

  admin-user:
    default: admin
    description: Default admin user for keystone
    type: string
  admin-role:
    default: Admin
    description: Admin role to be associated with admin and service users
    type: string
  service-tenant:
    default: services
    description: Name of tenant to associate with service credentials
    type: string

  os-admin-hostname:
    default:
    description: |
      The hostname or address of the admin endpoints that should be advertised
      in the keystone identity provider.
    type: string
  os-internal-hostname:
    default:
    description: |
      The hostname or address of the internal endpoints that should be advertised
      in the keystone identity provider.
    type: string
  os-public-hostname:
    default:
    description: |
      The hostname or address of the internal endpoints that should be advertised
      in the keystone identity provider.
    type: string
  region:
    default: RegionOne
    description: Space delimited list of OpenStack regions
    type: string

  fernet-max-active-keys:
    type: int
    default: 3
    description: |
      This is the maximum number of active keys. It has a minimum of 3, which includes the
      spare and staging keys. The key rotation time is calculated by:

      rotation-time = (token-expiration + allow-expired-window) / (fernet-max-active-keys - 2)

      Please see the charm documentation for further details about how to use the Fernet token
      parameters to achieve a key strategy appropriate for the system in question.
      NOTE: the minimum time between fernet key rotations is 5 minutes;
      token-expiration + allow-expired-window should not be less than this.
  token-expiration:
    type: int
    default: 3600 # 1 hour
    description: |
      Amount of time (in seconds) a token should remain valid.
      Default is 1 hour.
  allow-expired-window:
    type: int
    default: 172800 # 2 days
    description: |
      This controls the number of seconds that a token can be retrieved for beyond the built-in expiry time.
      This allows long running operations to succeed.
      Defaults to two days.
  catalog-cache-expiration:
    type: int
    default: 60
    description: Amount of time (in seconds) the catalog should be cached for.
  dogpile-cache-expiration:
    type: int
    default: 60
    description: |
      Amount of time (in seconds) to cache items in the dogpile.cache. This only applies
      to cached methods that do not have an explicitly defined cache expiration time.

  identity-backend:
    type: string
    default: "sql"
    description: |
      Keystone identity backend, valid options are sql and pam

